/**
 * Cross-implementation HYBRID post-quantum key verification: the SDK's
 * `HybridKeypair` / `HdWallet.deriveHybridKeypair` (`src/hybrid.ts`) must derive
 * — byte-for-byte — the SAME Ed25519 + ML-DSA-65 (FIPS 204) key the Rust node
 * does (`Keypair::hybrid_from_seed`, exposed via `sov-wallet import`). The vector
 * `vectors/hybrid-key.json` is generated by the authoritative Rust side. Matching
 * it proves the two `@noble/post-quantum`/`fips204` implementations, the Blake3
 * domain separation, and the on-chain encoding all agree.
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { HdWallet } from "../src/hd.js";
import { HybridKeypair, HybridPublicKey, HybridSignature } from "../src/hybrid.js";
import { buildAndSign, verifyBuiltSignature } from "../src/tx-builder.js";
import { encodeSignedTransaction } from "../src/borsh.js";

interface HybridVector {
  mnemonic: string;
  account: number;
  index: number;
  leaf_seed_hex: string;
  hybrid_public_key: string;
  hybrid_shielded: string;
  ed25519_public_key: string;
}

const here = dirname(fileURLToPath(import.meta.url));
const vector: HybridVector = JSON.parse(
  readFileSync(join(here, "..", "vectors", "hybrid-key.json"), "utf8"),
);

const hex = (b: Uint8Array): string => Buffer.from(b).toString("hex");

describe("hybrid Ed25519 + ML-DSA-65 keys (cross-impl with the Rust node)", () => {
  it("derives the exact hybrid public key the Rust node derives (KAT)", () => {
    const wallet = HdWallet.fromMnemonic(vector.mnemonic);
    const kp = wallet.deriveHybridKeypair(vector.account, vector.index);
    // The single most important guarantee: same mnemonic -> same hybrid key,
    // byte-for-byte, in TypeScript and Rust.
    expect(kp.publicKey.toJSON()).toBe(vector.hybrid_public_key);
    expect(kp.publicKey.scheme).toBe("hybrid65");
    // Components: 32-byte Ed25519 + 1952-byte ML-DSA-65.
    expect(kp.publicKey.ed25519.length).toBe(32);
    expect(kp.publicKey.mlDsa.length).toBe(1952);
  });

  it("derives the identical SLIP-0010 leaf seed as Rust", () => {
    const wallet = HdWallet.fromMnemonic(vector.mnemonic);
    expect(hex(wallet.deriveSeed(vector.account, vector.index))).toBe(vector.leaf_seed_hex);
  });

  it("still derives the Ed25519 key Rust pins (legacy/parity scheme)", () => {
    const wallet = HdWallet.fromMnemonic(vector.mnemonic);
    expect(wallet.deriveKeypair(vector.account, vector.index).publicKey.toJSON()).toBe(
      vector.ed25519_public_key,
    );
  });

  it("HybridKeypair.fromSeed reproduces the same key from the leaf seed", () => {
    const seed = Uint8Array.from(Buffer.from(vector.leaf_seed_hex, "hex"));
    expect(HybridKeypair.fromSeed(seed).publicKey.toJSON()).toBe(vector.hybrid_public_key);
  });

  it("signs deterministically and verifies (conjunction of both components)", () => {
    const seed = Uint8Array.from(Buffer.from(vector.leaf_seed_hex, "hex"));
    const kp = HybridKeypair.fromSeed(seed);
    const msg = new TextEncoder().encode("rotate the reserve to post-quantum keys");
    const sig = kp.sign(msg);

    expect(sig.scheme).toBe("hybrid65");
    expect(sig.ed25519.length).toBe(64);
    expect(sig.mlDsa.length).toBe(3309);
    // Deterministic: the seed-derived ML-DSA randomness makes signing reproducible.
    expect(kp.sign(msg).toJSON()).toBe(sig.toJSON());
    // Verifies; a tampered message does not.
    expect(kp.publicKey.verify(msg, sig)).toBe(true);
    expect(kp.publicKey.verify(new TextEncoder().encode("different"), sig)).toBe(false);
  });

  it("verification is a CONJUNCTION — a corrupted half is rejected", () => {
    const seed = Uint8Array.from(Buffer.from(vector.leaf_seed_hex, "hex"));
    const kp = HybridKeypair.fromSeed(seed);
    const msg = new TextEncoder().encode("hybrid conjunction");
    const sig = kp.sign(msg);

    const badMl = Uint8Array.from(sig.mlDsa);
    badMl[0] ^= 0xff;
    expect(kp.publicKey.verify(msg, new HybridSignature(sig.ed25519, badMl))).toBe(false);

    const badEd = Uint8Array.from(sig.ed25519);
    badEd[0] ^= 0xff;
    expect(kp.publicKey.verify(msg, new HybridSignature(badEd, sig.mlDsa))).toBe(false);
  });

  it("round-trips the hybrid public key/signature hex form", () => {
    const seed = Uint8Array.from(Buffer.from(vector.leaf_seed_hex, "hex"));
    const kp = HybridKeypair.fromSeed(seed);
    const sig = kp.sign(new TextEncoder().encode("round trip"));
    expect(HybridPublicKey.fromHex(kp.publicKey.toJSON()).toJSON()).toBe(kp.publicKey.toJSON());
    expect(HybridSignature.fromHex(sig.toJSON()).toJSON()).toBe(sig.toJSON());
  });

  it("builds a wire transaction signed by the hybrid key (Borsh scheme 0x01)", () => {
    const wallet = HdWallet.fromMnemonic(vector.mnemonic);
    const kp = wallet.deriveHybridKeypair(0, 0);
    const signed = buildAndSign({
      signer: "josh.wallet.sov",
      keypair: kp,
      nonce: 0,
      action: { type: "transfer", to: "faucet.reserve.sov", amount: "1000000000" },
    });
    // The committed key and signature both carry the hybrid scheme.
    expect(signed.transaction.public_key.startsWith("hybrid65:0x")).toBe(true);
    expect(signed.signature.startsWith("hybrid65:0x")).toBe(true);
    // The SDK verifies its own hybrid signature over the canonical Borsh bytes.
    expect(verifyBuiltSignature(signed)).toBe(true);
    // The full wire encoding ends with scheme byte 0x01 + (64 + 3309) sig bytes.
    const wire = encodeSignedTransaction(signed);
    const sigStart = wire.length - (1 + 64 + 3309);
    expect(wire[sigStart]).toBe(0x01);
  });
});
