/**
 * Cross-implementation STATE verification: the SDK's independent re-derivation of
 * SOV's authenticated world state — Sparse Merkle Tree slots, Borsh-encoded
 * account values, the `state_root`, and inclusion/exclusion Merkle proofs — must
 * equal, byte-for-byte, a state vector generated by the Rust node
 * (`cargo run -p sov-rpc --bin sov-katgen -- state > sdk/vectors/state.json`).
 * This proves the second (TypeScript) implementation agrees with the node on
 * authenticated state, not just on block/transaction hashing.
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { hexToBytes } from "../src/borsh.js";
import { SparseMerkleTree, verifyMerkleProof } from "../src/smt.js";
import {
  accountSlot,
  computeStateRoot,
  encodeAccount,
  type AccountState,
  type NamedAccount,
} from "../src/state.js";
import { verifyStateRoot } from "../src/verify.js";

interface VectorAccount {
  id: string;
  nonce: number;
  balance: string;
  locked: string;
  unlock_height: number;
  public_key_hex: string | null;
  code_hex: string | null;
  slot: string;
  value_borsh_hex: string;
}
interface VectorProof {
  id: string;
  slot: string;
  value_borsh_hex?: string;
  leaf: string;
  siblings: string[];
}
interface StateVector {
  state_root: string;
  accounts: VectorAccount[];
  inclusion_proof: VectorProof;
  exclusion_proof: VectorProof;
}

const here = dirname(fileURLToPath(import.meta.url));
const vec: StateVector = JSON.parse(readFileSync(join(here, "..", "vectors", "state.json"), "utf8"));

const norm = (h: string): string => (h.startsWith("0x") ? h.slice(2) : h).toLowerCase();
const toHex = (b: Uint8Array): string => Buffer.from(b).toString("hex");

const toAccountState = (a: VectorAccount): AccountState => ({
  nonce: a.nonce,
  balance: a.balance,
  locked: a.locked,
  unlockHeight: a.unlock_height,
  publicKey: a.public_key_hex,
  code: a.code_hex === null ? null : hexToBytes(a.code_hex),
});

const named: NamedAccount[] = vec.accounts.map((a) => ({ id: a.id, account: toAccountState(a) }));

describe("cross-impl state verification (byte-for-byte parity with the Rust node)", () => {
  it("independently derives each account's Merkle slot", () => {
    for (const a of vec.accounts) {
      expect(toHex(accountSlot(a.id))).toBe(norm(a.slot));
    }
  });

  it("independently Borsh-encodes each account value", () => {
    for (const a of vec.accounts) {
      expect(toHex(encodeAccount(toAccountState(a)))).toBe(norm(a.value_borsh_hex));
    }
  });

  it("reconstructs the state_root from the account set", () => {
    expect(norm(computeStateRoot(named))).toBe(norm(vec.state_root));
  });

  it("verifyStateRoot accepts the matching account set", () => {
    const result = verifyStateRoot(named, vec.state_root);
    expect(result.ok).toBe(true);
    expect(norm(result.computed)).toBe(norm(vec.state_root));
  });

  it("verifyStateRoot rejects a tampered balance", () => {
    const tampered = named.map((n, i) =>
      i === 0 ? { ...n, account: { ...n.account, balance: "1" } } : n,
    );
    expect(verifyStateRoot(tampered, vec.state_root).ok).toBe(false);
  });

  it("verifies the node's inclusion proof against the state_root", () => {
    const p = vec.inclusion_proof;
    const value = hexToBytes(p.value_borsh_hex as string);
    const ok = verifyMerkleProof(
      hexToBytes(vec.state_root),
      hexToBytes(p.slot),
      value,
      { leaf: hexToBytes(p.leaf), siblings: p.siblings.map(hexToBytes) },
    );
    expect(ok).toBe(true);
    // A wrong value must not verify against the same proof.
    expect(
      verifyMerkleProof(hexToBytes(vec.state_root), hexToBytes(p.slot), hexToBytes("00".repeat(8)), {
        leaf: hexToBytes(p.leaf),
        siblings: p.siblings.map(hexToBytes),
      }),
    ).toBe(false);
  });

  it("verifies the node's exclusion proof against the state_root", () => {
    const p = vec.exclusion_proof;
    const ok = verifyMerkleProof(
      hexToBytes(vec.state_root),
      hexToBytes(p.slot),
      null,
      { leaf: hexToBytes(p.leaf), siblings: p.siblings.map(hexToBytes) },
    );
    expect(ok).toBe(true);
    // Claiming a value for an absent key must fail.
    expect(
      verifyMerkleProof(hexToBytes(vec.state_root), hexToBytes(p.slot), hexToBytes("00".repeat(8)), {
        leaf: hexToBytes(p.leaf),
        siblings: p.siblings.map(hexToBytes),
      }),
    ).toBe(false);
  });

  it("regenerates the node's inclusion/exclusion proofs byte-for-byte", () => {
    const tree = new SparseMerkleTree();
    for (const { id, account } of named) tree.insert(accountSlot(id), encodeAccount(account));

    const inc = tree.prove(hexToBytes(vec.inclusion_proof.slot));
    expect(toHex(inc.leaf)).toBe(norm(vec.inclusion_proof.leaf));
    expect(inc.siblings.map(toHex)).toEqual(vec.inclusion_proof.siblings.map(norm));

    const exc = tree.prove(hexToBytes(vec.exclusion_proof.slot));
    expect(toHex(exc.leaf)).toBe(norm(vec.exclusion_proof.leaf));
    expect(exc.siblings.map(toHex)).toEqual(vec.exclusion_proof.siblings.map(norm));
  });
});
