/**
 * Cross-implementation STATE-TRANSITION verification: the SDK's independent
 * re-execution of a real block (`sdk/src/stf.ts`) must DERIVE — byte-for-byte —
 * the same post-state the Rust node's runtime produced: `state_root`,
 * `receipts_root`, every account, and every receipt. The vector is generated by
 * the node itself (`cargo run -p sov-rpc --bin sov-katgen -- stf >
 * sdk/vectors/stf.json`) by executing the block through the production STF.
 *
 * This is the second client actually RE-EXECUTING consensus — applying transfers,
 * a vesting claim, a contract
 * deploy, an HTLC lock+claim atomic-swap settlement, the fee burn/tip-split, and
 * a transfer that fails for insufficient balance — and arriving independently at
 * the node's result.
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  applyCoinbase,
  applyTransactions,
  Ledger,
  receiptsRoot,
  type BlockContext,
} from "../src/stf.js";
import type { AccountState } from "../src/state.js";
import type { Receipt, SignedTransaction } from "../src/types.js";

interface VecAccount {
  id: string;
  nonce: number;
  balance: string;
  locked: string;
  unlock_height: number;
  public_key_hex: string | null;
  code_hex: string | null;
}
interface StfVector {
  policy: {
    gas_price: string;
    max_code_bytes: number;
    base_reward: string;
    halving_interval_blocks: number;
    mining_budget_grains: string;
  };
  context: { height: number; prev_hash: string; miner: string };
  coinbase: { miner: string; reward: string };
  prev_accounts: VecAccount[];
  transactions: SignedTransaction[];
  post_state_root: string;
  post_receipts_root: string;
  post_accounts: VecAccount[];
  receipts: Receipt[];
}

const here = dirname(fileURLToPath(import.meta.url));
const vec: StfVector = JSON.parse(readFileSync(join(here, "..", "vectors", "stf.json"), "utf8"));

const norm = (h: string): string => (h.startsWith("0x") ? h.slice(2) : h).toLowerCase();

const toAccountState = (a: VecAccount): AccountState => ({
  nonce: a.nonce,
  balance: a.balance,
  locked: a.locked,
  unlockHeight: a.unlock_height,
  publicKey: a.public_key_hex,
  code: a.code_hex === null ? null : Buffer.from(a.code_hex, "hex"),
});

const ctx: BlockContext = {
  height: vec.context.height,
  gasPrice: BigInt(vec.policy.gas_price),
  maxCodeBytes: vec.policy.max_code_bytes,
  miner: vec.context.miner,
  baseReward: BigInt(vec.policy.base_reward),
  halvingIntervalBlocks: BigInt(vec.policy.halving_interval_blocks),
  miningBudgetGrains: BigInt(vec.policy.mining_budget_grains),
};

// Compare an independently-produced account set to the node's post-state.
const accountKey = (a: { id: string; account: AccountState }) => ({
  id: a.id,
  nonce: Number(a.account.nonce),
  balance: BigInt(a.account.balance).toString(),
  locked: BigInt(a.account.locked).toString(),
  unlock_height: Number(a.account.unlockHeight),
  public_key: a.account.publicKey ? norm(a.account.publicKey) : null,
  code:
    a.account.code == null
      ? null
      : Buffer.from(a.account.code instanceof Uint8Array ? a.account.code : Uint8Array.from(a.account.code)).toString(
          "hex",
        ),
});

const vecAccountKey = (a: VecAccount) => ({
  id: a.id,
  nonce: a.nonce,
  balance: a.balance,
  locked: a.locked,
  unlock_height: a.unlock_height,
  public_key: a.public_key_hex ? norm(a.public_key_hex) : null,
  code: a.code_hex === null ? null : norm(a.code_hex),
});

function freshLedger(): Ledger {
  return Ledger.fromAccounts(
    vec.prev_accounts.map((a) => ({ id: a.id, account: toAccountState(a) })),
  );
}

describe("cross-impl STF re-execution (byte-for-byte parity with the Rust node)", () => {
  it("mints the Bitcoin-schedule coinbase entirely to the miner before the transactions", () => {
    const ledger = freshLedger();
    const reward = applyCoinbase(ledger, ctx);
    // Independently derived subsidy equals the node's minted amount...
    expect(reward.toString()).toBe(vec.coinbase.reward);
    // ...the whole reward is newly issued (mined counter advances by the total)...
    expect(ledger.minedEmittedGrains()).toBe(reward);
    // ...and the ENTIRE reward goes to the miner — no tax, nothing burned.
    const find = (id: string) =>
      BigInt(ledger.accountStates().find((a) => a.id === id)?.account.balance ?? 0n);
    expect(find(vec.coinbase.miner)).toBe(reward);
  });

  it("derives the same post-state state_root", () => {
    const ledger = freshLedger();
    applyCoinbase(ledger, ctx);
    applyTransactions(ledger, vec.transactions, ctx);
    expect(norm(ledger.stateRoot())).toBe(norm(vec.post_state_root));
  });

  it("derives the same receipts (status + gas) and receipts_root", () => {
    const ledger = freshLedger();
    const receipts = applyTransactions(ledger, vec.transactions, ctx);

    expect(receipts.length).toBe(vec.receipts.length);
    receipts.forEach((r, i) => {
      const want = vec.receipts[i] as Receipt;
      expect(norm(r.tx_id)).toBe(norm(want.tx_id));
      expect(r.status).toEqual(want.status);
      expect(r.gas_used).toBe(want.gas_used);
    });

    expect(norm(receiptsRoot(receipts))).toBe(norm(vec.post_receipts_root));
  });

  it("derives the same final account set", () => {
    const ledger = freshLedger();
    applyCoinbase(ledger, ctx);
    applyTransactions(ledger, vec.transactions, ctx);

    const got = ledger
      .accountStates()
      .map(accountKey)
      .sort((a, b) => a.id.localeCompare(b.id));
    const want = vec.post_accounts.map(vecAccountKey).sort((a, b) => a.id.localeCompare(b.id));
    expect(got).toEqual(want);
  });

  it("records the failing transfer as a Failed receipt but still advances its nonce", () => {
    const ledger = freshLedger();
    const receipts = applyTransactions(ledger, vec.transactions, ctx);
    const failed = receipts.find((r) => r.status.status === "failed");
    expect(failed).toBeDefined();
    expect(failed?.status).toEqual({ status: "failed", reason: "insufficient balance" });
    // The sender (ecb) still had its nonce advanced and fee charged.
    const ecb = ledger.accountStates().find((a) => a.id === "ecb.reserve.sov");
    expect(Number(ecb?.account.nonce)).toBe(1);
  });

  it("rejects a block whose signature has been tampered", () => {
    const ledger = freshLedger();
    const tampered = vec.transactions.map((t, i) =>
      i === 0 ? { ...t, signature: "0x" + "00".repeat(64) } : t,
    );
    expect(() => applyTransactions(ledger, tampered, ctx)).toThrow(/signature/i);
  });
});
