/**
 * Cross-implementation block verification: the SDK's independent re-derivation of
 * SOV's consensus commitments (block id, transaction Merkle root, transaction ids)
 * must equal, byte-for-byte, a block vector generated by the Rust node
 * (`cargo run -p sov-rpc --bin sov-katgen -- block > sdk/vectors/block.json`).
 * This is the proof that the second (TypeScript) implementation agrees with the
 * node on consensus hashing — the core value of an independent client.
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { blockHash, computeTxRoot, merkleRoot, transactionId } from "../src/borsh.js";
import { verifyBlockDigest } from "../src/verify.js";
import type { Block, BlockHeader, Transaction } from "../src/types.js";

interface BlockVector {
  block_hash: string;
  header: BlockHeader;
  tx_ids: string[];
  transactions: { signer: string; public_key_hex: string; nonce: number; action: Transaction["action"] }[];
}

const here = dirname(fileURLToPath(import.meta.url));
const vec: BlockVector = JSON.parse(readFileSync(join(here, "..", "vectors", "block.json"), "utf8"));

const norm = (h: string): string => (h.startsWith("0x") ? h.slice(2) : h).toLowerCase();
const txs: Transaction[] = vec.transactions.map((t) => ({
  signer: t.signer,
  public_key: t.public_key_hex,
  nonce: t.nonce,
  action: t.action,
}));

describe("cross-impl block verification (byte-for-byte parity with the Rust node)", () => {
  it("recomputes each transaction id", () => {
    txs.forEach((tx, i) => expect(norm(transactionId(tx))).toBe(norm(vec.tx_ids[i])));
  });

  it("recomputes the transaction Merkle root in the header", () => {
    expect(norm(computeTxRoot(txs))).toBe(norm(vec.header.tx_root));
  });

  it("recomputes the block id (header hash)", () => {
    expect(norm(blockHash(vec.header))).toBe(norm(vec.block_hash));
  });

  it("verifyBlockDigest accepts the matching block + digest", () => {
    const block: Block = {
      header: vec.header,
      transactions: txs.map((transaction) => ({ transaction, signature: "0x" + "00".repeat(64) })),
    };
    const result = verifyBlockDigest(block, { hash: vec.block_hash, txIds: vec.tx_ids });
    expect(result.issues).toEqual([]);
    expect(result.ok).toBe(true);
  });

  it("verifyBlockDigest rejects a tampered block hash and tx_root", () => {
    const tampered: Block = {
      header: { ...vec.header, tx_root: "0x" + "11".repeat(32) },
      transactions: txs.map((transaction) => ({ transaction, signature: "0x" + "00".repeat(64) })),
    };
    const result = verifyBlockDigest(tampered, { hash: "0x" + "22".repeat(32), txIds: vec.tx_ids });
    expect(result.ok).toBe(false);
    expect(result.issues.length).toBeGreaterThan(0);
  });
});

describe("merkle root edge cases (mirror the node)", () => {
  it("is order-sensitive", () => {
    const a = new Uint8Array(32).fill(1);
    const b = new Uint8Array(32).fill(2);
    const toHex = (x: Uint8Array) => Buffer.from(x).toString("hex");
    expect(toHex(merkleRoot([a, b]))).not.toBe(toHex(merkleRoot([b, a])));
  });

  it("empty and single-leaf are well-defined and distinct", () => {
    const leaf = new Uint8Array(32).fill(7);
    const toHex = (x: Uint8Array) => Buffer.from(x).toString("hex");
    expect(toHex(merkleRoot([]))).not.toBe(toHex(merkleRoot([leaf])));
  });
});
