// AUTO-GENERATED by dashboard/gen-status.mjs — DO NOT EDIT BY HAND.
// Every value below is derived from real repo state. Refresh with:
//   node dashboard/gen-status.mjs
window.SOV_STATUS = {
  "generatedAt": "2026-06-01T19:55:09.631Z",
  "generator": "dashboard/gen-status.mjs",
  "repoRoot": "/Users/josh/github/sov",
  "chain": {
    "crateCount": 28,
    "crates": [
      {
        "dir": "accounts",
        "name": "sov-accounts",
        "rustFiles": 4,
        "loc": 903,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 21,
          "failed": 0
        }
      },
      {
        "dir": "bridge",
        "name": "sov-bridge",
        "rustFiles": 7,
        "loc": 1448,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 19,
          "failed": 0
        }
      },
      {
        "dir": "captable",
        "name": "sov-captable",
        "rustFiles": 1,
        "loc": 216,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 6,
          "failed": 0
        }
      },
      {
        "dir": "chain",
        "name": "sov-chain",
        "rustFiles": 3,
        "loc": 1428,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 19,
          "failed": 0
        }
      },
      {
        "dir": "compliance",
        "name": "sov-compliance",
        "rustFiles": 3,
        "loc": 687,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 15,
          "failed": 0
        }
      },
      {
        "dir": "compute",
        "name": "sov-compute",
        "rustFiles": 9,
        "loc": 2981,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 37,
          "failed": 0
        }
      },
      {
        "dir": "confidential",
        "name": "sov-confidential",
        "rustFiles": 4,
        "loc": 452,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 12,
          "failed": 0
        }
      },
      {
        "dir": "consensus",
        "name": "sov-consensus",
        "rustFiles": 4,
        "loc": 659,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 12,
          "failed": 0
        }
      },
      {
        "dir": "crypto",
        "name": "sov-crypto",
        "rustFiles": 4,
        "loc": 381,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 12,
          "failed": 0
        }
      },
      {
        "dir": "governance",
        "name": "sov-governance",
        "rustFiles": 1,
        "loc": 1033,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 18,
          "failed": 0
        }
      },
      {
        "dir": "intents",
        "name": "sov-intents",
        "rustFiles": 1,
        "loc": 406,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 6,
          "failed": 0
        }
      },
      {
        "dir": "mempool",
        "name": "sov-mempool",
        "rustFiles": 1,
        "loc": 340,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 9,
          "failed": 0
        }
      },
      {
        "dir": "mining",
        "name": "sov-mining",
        "rustFiles": 2,
        "loc": 391,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 10,
          "failed": 0
        }
      },
      {
        "dir": "mpc",
        "name": "sov-mpc",
        "rustFiles": 3,
        "loc": 401,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 6,
          "failed": 0
        }
      },
      {
        "dir": "network",
        "name": "sov-network",
        "rustFiles": 4,
        "loc": 631,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 9,
          "failed": 0
        }
      },
      {
        "dir": "node",
        "name": "sov-node",
        "rustFiles": 4,
        "loc": 723,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": true,
        "bins": [
          "sov-miner"
        ],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library + binary (main) + 1 bin",
        "tests": {
          "attributed": true,
          "passed": 6,
          "failed": 0
        }
      },
      {
        "dir": "pow",
        "name": "sov-pow",
        "rustFiles": 3,
        "loc": 312,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 9,
          "failed": 0
        }
      },
      {
        "dir": "primitives",
        "name": "sov-primitives",
        "rustFiles": 5,
        "loc": 667,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 21,
          "failed": 0
        }
      },
      {
        "dir": "reserve",
        "name": "sov-reserve",
        "rustFiles": 8,
        "loc": 1814,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 38,
          "failed": 0
        }
      },
      {
        "dir": "rpc",
        "name": "sov-rpc",
        "rustFiles": 12,
        "loc": 2715,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [
          "sov-katgen",
          "sov-rpc-miner",
          "sov-rpcd",
          "sov-wallet"
        ],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library + 4 bins",
        "tests": {
          "attributed": true,
          "passed": 15,
          "failed": 0
        }
      },
      {
        "dir": "runtime",
        "name": "sov-runtime",
        "rustFiles": 3,
        "loc": 1136,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 17,
          "failed": 0
        }
      },
      {
        "dir": "sharding",
        "name": "sov-sharding",
        "rustFiles": 4,
        "loc": 1482,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 20,
          "failed": 0
        }
      },
      {
        "dir": "staking",
        "name": "sov-staking",
        "rustFiles": 1,
        "loc": 133,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 4,
          "failed": 0
        }
      },
      {
        "dir": "state",
        "name": "sov-state",
        "rustFiles": 4,
        "loc": 984,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 20,
          "failed": 0
        }
      },
      {
        "dir": "types",
        "name": "sov-types",
        "rustFiles": 4,
        "loc": 566,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 17,
          "failed": 0
        }
      },
      {
        "dir": "verify",
        "name": "sov-verify",
        "rustFiles": 9,
        "loc": 1467,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 31,
          "failed": 0
        }
      },
      {
        "dir": "vm",
        "name": "sov-vm",
        "rustFiles": 3,
        "loc": 405,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 7,
          "failed": 0
        }
      },
      {
        "dir": "wallet",
        "name": "sov-wallet",
        "rustFiles": 1,
        "loc": 172,
        "inWorkspace": true,
        "hasLib": true,
        "hasMain": false,
        "bins": [],
        "hasBuildTarget": true,
        "state": "active",
        "kind": "library",
        "tests": {
          "attributed": true,
          "passed": 4,
          "failed": 0
        }
      }
    ],
    "rustFiles": 112,
    "rustLoc": 24933,
    "tests": {
      "ran": true,
      "status": "passing",
      "passed": 416,
      "failed": 0,
      "message": "All 416 tests passing",
      "perBinary": {
        "sov_accounts": {
          "passed": 21,
          "failed": 0
        },
        "sov_bridge": {
          "passed": 19,
          "failed": 0
        },
        "sov_captable": {
          "passed": 6,
          "failed": 0
        },
        "sov_chain": {
          "passed": 19,
          "failed": 0
        },
        "sov_compliance": {
          "passed": 15,
          "failed": 0
        },
        "sov_compute": {
          "passed": 37,
          "failed": 0
        },
        "sov_confidential": {
          "passed": 12,
          "failed": 0
        },
        "sov_consensus": {
          "passed": 12,
          "failed": 0
        },
        "sov_crypto": {
          "passed": 12,
          "failed": 0
        },
        "sov_governance": {
          "passed": 18,
          "failed": 0
        },
        "sov_intents": {
          "passed": 6,
          "failed": 0
        },
        "sov_mempool": {
          "passed": 9,
          "failed": 0
        },
        "sov_mining": {
          "passed": 10,
          "failed": 0
        },
        "sov_mpc": {
          "passed": 6,
          "failed": 0
        },
        "sov_network": {
          "passed": 9,
          "failed": 0
        },
        "sov_node": {
          "passed": 6,
          "failed": 0
        },
        "sov_miner": {
          "passed": 0,
          "failed": 0
        },
        "sov_pow": {
          "passed": 9,
          "failed": 0
        },
        "sov_primitives": {
          "passed": 21,
          "failed": 0
        },
        "sov_reserve": {
          "passed": 38,
          "failed": 0
        },
        "sov_rpc": {
          "passed": 1,
          "failed": 0
        },
        "sov_katgen": {
          "passed": 0,
          "failed": 0
        },
        "sov_rpc_miner": {
          "passed": 0,
          "failed": 0
        },
        "sov_rpcd": {
          "passed": 0,
          "failed": 0
        },
        "sov_wallet": {
          "passed": 4,
          "failed": 0
        },
        "client": {
          "passed": 1,
          "failed": 0
        },
        "daemon": {
          "passed": 3,
          "failed": 0
        },
        "p2p": {
          "passed": 4,
          "failed": 0
        },
        "rpc": {
          "passed": 2,
          "failed": 0
        },
        "sov_runtime": {
          "passed": 17,
          "failed": 0
        },
        "sov_sharding": {
          "passed": 20,
          "failed": 0
        },
        "sov_staking": {
          "passed": 4,
          "failed": 0
        },
        "sov_state": {
          "passed": 20,
          "failed": 0
        },
        "sov_types": {
          "passed": 17,
          "failed": 0
        },
        "sov_verify": {
          "passed": 12,
          "failed": 0
        },
        "chaos": {
          "passed": 1,
          "failed": 0
        },
        "conformance": {
          "passed": 3,
          "failed": 0
        },
        "consensus_model": {
          "passed": 2,
          "failed": 0
        },
        "fault_injection": {
          "passed": 5,
          "failed": 0
        },
        "kat": {
          "passed": 1,
          "failed": 0
        },
        "properties": {
          "passed": 6,
          "failed": 0
        },
        "replay": {
          "passed": 1,
          "failed": 0
        },
        "sov_vm": {
          "passed": 6,
          "failed": 0
        },
        "contract": {
          "passed": 1,
          "failed": 0
        }
      }
    }
  },
  "explorer": {
    "exists": true,
    "hasPackageJson": true,
    "sourceFiles": 13,
    "status": "in_progress",
    "message": "13 source file(s) present"
  },
  "progress": {
    "percent": 98,
    "doneItems": 59,
    "totalItems": 60,
    "inProgressItems": 1,
    "todoItems": 0
  },
  "roadmapIntro": "This is our living build list, ordered by dependency. Each item is something we implement and check off as we go. We build bottom-up: foundations first, advanced sovereign tooling last. The Done lane and overall build % are driven by real done flags verified against the repository.",
  "phases": [
    {
      "id": 0,
      "title": "Phase 0 — Foundations",
      "tag": "Bootstrap",
      "description": null,
      "items": [
        {
          "id": "p0-i0",
          "text": "Repo scaffolding, toolchain (Rust workspace), CI & test harness",
          "done": true,
          "status": "done",
          "note": "COMPLETE: Cargo workspace, rustfmt config, and a GitHub Actions CI workflow (.github/workflows/ci.yml): a lint job (fmt --check + clippy -D warnings) plus a build+test MATRIX across Linux, macOS, and Windows — so the clients are proven cross-platform on every push. cargo test + clippy currently clean locally (macOS)."
        },
        {
          "id": "p0-i1",
          "text": "Core data types: blocks, transactions, accounts, receipts",
          "done": true,
          "status": "done",
          "note": "COMPLETE: AccountId/Balance/Hash/BlockHeight in sov-primitives; Transaction/SignedTransaction, Block/BlockHeader, Receipt in sov-types — all with Borsh + JSON encodings and tests (signature verify, Merkle tx_root, receipts_root)."
        },
        {
          "id": "p0-i2",
          "text": "Cryptographic primitives: hashing, Ed25519 signatures, Merkle/Patricia trie",
          "done": true,
          "status": "done",
          "note": "COMPLETE: Blake3 hashing, Ed25519 sign/verify, and a domain-separated Merkle root in sov-crypto, plus a Sparse Merkle Tree authenticated state trie (inclusion/exclusion proofs) in sov-state. All tested."
        },
        {
          "id": "p0-i3",
          "text": "Key management & basic wallet",
          "done": true,
          "status": "done",
          "note": "COMPLETE: sov-wallet manages keypairs (generate/import), exposes public keys, and builds signed transfers; sov-crypto provides keypair generation + signing. In-memory keystore; encrypted at-rest storage is a future enhancement."
        }
      ],
      "doneCount": 4,
      "totalCount": 4,
      "percent": 100
    },
    {
      "id": 1,
      "title": "Phase 1 — Core Protocol",
      "tag": "Chain",
      "description": null,
      "items": [
        {
          "id": "p1-i0",
          "text": "State machine & persistent storage (trie-backed key-value store)",
          "done": true,
          "status": "done",
          "note": "COMPLETE: state machine (sov-runtime execution) + trie-backed key-value store (sov-state Ledger over a Sparse Merkle Tree) + durable persistence (Ledger save/load, tested to reproduce the exact state_root across reload). Persistence is snapshot-based; an incremental on-disk DB backend (e.g. RocksDB) is a future optimization."
        },
        {
          "id": "p1-i1",
          "text": "Transaction pool (mempool) & execution engine",
          "done": true,
          "status": "done",
          "note": "COMPLETE: sov-mempool (validated, nonce-ordered pool with capacity, dedup, contiguous-batch selection) and sov-runtime (authenticated, authorized, gas-metered execution producing receipts). Both tested."
        },
        {
          "id": "p1-i2",
          "text": "Doomslug-style PoS block production & sub-second finality",
          "done": true,
          "status": "done",
          "note": "COMPLETE: stake-weighted deterministic proposer selection + block production (sov-node) + multi-validator BFT supermajority finality (sov-consensus, tested to require >2/3 stake across distinct validators). Finality is single-round, hence sub-second by construction. A wall-clock slot scheduler is a thin runner on top; networked multi-node propagation is covered by the P2P item."
        },
        {
          "id": "p1-i3",
          "text": "P2P networking, peer discovery & block/tx gossip",
          "done": true,
          "status": "done",
          "note": "COMPLETE: real TCP transport (sov-network TcpNode) with length-prefixed framing, gossip broadcast of blocks/txs/approvals, and transitive peer discovery via address gossip — tested over loopback (delivery + A-discovers-C-through-B). An in-memory transport exists for deterministic tests. Authenticated handshake and graceful shutdown are future hardening."
        },
        {
          "id": "p1-i4",
          "text": "ASIC-resistant Nakamoto PoW: RandomX seal, Bitcoin emission",
          "done": true,
          "status": "done",
          "note": "SUPERSEDED by the Nakamoto migration: the mainnet seal is Monero's RandomX (memory-hard, ASIC-resistant, M-series-friendly) via audited randomx-rs, genesis-fixed PowAlgo (Sha256d for dev/test); committed difficulty in Bitcoin nBits; 50-SOV coinbase halving every 210,000 blocks, no pre-mine; epoch difficulty retargeting. Equihash and the old Mine/mint-layer model were removed; PoW IS consensus (no PoS)."
        }
      ],
      "doneCount": 5,
      "totalCount": 5,
      "percent": 100
    },
    {
      "id": 2,
      "title": "Phase 2 — Tokenomics & Staking",
      "tag": "Economics",
      "description": null,
      "items": [
        {
          "id": "p2-i0",
          "text": "SOV native token with capped supply (10–21M)",
          "done": true,
          "status": "done",
          "note": "COMPLETE: SOV is the native unit (Balance), 8 decimals — exactly Bitcoin/Zcash precision (1.00000000) — with a hard cap of 21,000,000 enforced everywhere new supply can appear: at genesis, the mining mint, and the staking-reward mint (all clamped to the cap)."
        },
        {
          "id": "p2-i1",
          "text": "Diminishing, predictable issuance schedule",
          "done": true,
          "status": "done",
          "note": "COMPLETE: emission comes from two deterministic, cap-bounded sources — the PoW mint (sov-mining: reward halves as supply grows) and staking rewards (sov-staking: lock-duration-weighted). Both are predictable functions of state and clamped to the cap. Tested."
        },
        {
          "id": "p2-i2",
          "text": "Time-locked staking & long-term reward curves",
          "done": true,
          "status": "done",
          "note": "COMPLETE: Stake/Unstake actions (sov-runtime) bond liquid balance with a height-based lock; sov-staking's reward curve scales linearly with lock duration (longer lock = larger reward, up to a cap). Unstake is blocked until the lock expires. Tested end-to-end through produced blocks."
        },
        {
          "id": "p2-i3",
          "text": "Vesting / lockup logic for early allocations",
          "done": true,
          "status": "done",
          "note": "COMPLETE: genesis VestingGrant locks an allocation until an unlock height; locked funds count toward supply but are non-spendable; a ClaimVesting action releases them to the liquid balance only at/after unlock. Tested through produced blocks."
        },
        {
          "id": "p2-i4",
          "text": "Anti-dumping & anti-collusion economic guards",
          "done": true,
          "status": "done",
          "note": "COMPLETE. Anti-dumping: staking lock (no early exit), minimum-lock floor, no-shortening on re-stake, vesting lockups, lock-weighted rewards — long-term holding is the dominant strategy. Anti-collusion: equivocation slashing — approvals are signed over (block_hash, height), so a validator double-signing two blocks at one height is cryptographically proven (Equivocation) and slashed; its stake is excluded from all finality tallies, destroying a colluder's weight the instant it cheats. Tested. (Automatic stake-burn at epoch rotation and hard stake-concentration caps — which conflict with single-validator devnets — are governance-layer follow-ons.)"
        }
      ],
      "doneCount": 5,
      "totalCount": 5,
      "percent": 100
    },
    {
      "id": 3,
      "title": "Phase 3 — Smart Contracts",
      "tag": "VM",
      "description": null,
      "items": [
        {
          "id": "p3-i0",
          "text": "WASM runtime integration & host functions",
          "done": true,
          "status": "done",
          "note": "COMPLETE: sov-vm — a deterministic, pure-Rust wasmi interpreter (portable to macOS/Windows/Linux, no JIT divergence). Host ABI (module 'env'): storage_read/storage_write over the contract's linear memory + block_height context, with no ambient authority. Tested with WAT contracts (storage round-trip, missing-entry, invalid-wasm)."
        },
        {
          "id": "p3-i1",
          "text": "Gas metering & fee model for high-value transfers",
          "done": true,
          "status": "done",
          "note": "COMPLETE: gas metering via wasmi fuel (out-of-gas traps, no state committed). On-chain Deploy/Call actions wire the VM into the runtime — contract code lives on its account and per-contract storage is committed to the state_root; a Call meters VM gas and charges the caller fee = gas_used × gas_price, paid to the block proposer. Tested at the runtime level (fee charged to caller, credited to collector) and end-to-end through real blocks (deploy + call the counter contract; on-chain storage increments). Gas price is a governance-tunable parameter (currently 0)."
        },
        {
          "id": "p3-i2",
          "text": "Contract SDK (Rust first, then JS/Python bindings)",
          "done": true,
          "status": "done",
          "note": "COMPLETE for Rust: contracts/sov-sdk is a no_std guest SDK (safe get/set/current_height wrappers over the host ABI, bump allocator, panic handler). An example `counter` contract is written in safe Rust, compiles to wasm32-unknown-unknown (578 bytes), and runs end-to-end on sov-vm — a committed test fixture (crates/vm/tests/counter.wasm) drives an integration test proving persisted state across calls. JS/Python bindings are a future extension."
        }
      ],
      "doneCount": 3,
      "totalCount": 3,
      "percent": 100
    },
    {
      "id": 4,
      "title": "Phase 4 — Scaling & Sharding",
      "tag": "Scale",
      "description": null,
      "items": [
        {
          "id": "p4-i0",
          "text": "Nightshade-style dynamic homogeneous sharding",
          "done": true,
          "status": "done",
          "note": "COMPLETE: sov-sharding is now a full parallel execution engine. ShardedState holds one isolated Ledger per shard (shards share no mutable account state); apply_round executes a block's transactions IN PARALLEL across shards (one OS thread per shard via std::thread::scope), reusing the canonical sov-runtime for every shard-local effect — no second, divergent state machine. Each shard emits a Chunk (txs, receipts, cross-shard receipts in/out, four Merkle roots + post-state root) that any verifier can re-execute and check INDEPENDENTLY (verify_chunk) — per-shard chunk consensus; the block commits to all chunks via chunks_root. Dynamic resharding is wired to live state: ShardedState::reshard re-buckets every account on split/merge with balances invariant. Execution is deterministic regardless of thread scheduling (tested). Tested. Remaining integration: making the sharded engine the chain's live block-production/consensus path (validators per shard in sov-chain) is a node-layer follow-on; the monolithic single-ledger Blockchain still drives the current devnet."
        },
        {
          "id": "p4-i1",
          "text": "Cross-shard messaging & receipts",
          "done": true,
          "status": "done",
          "note": "COMPLETE: asynchronous cross-shard execution. A transfer whose recipient lives on another shard is debited on the sender's shard immediately and emitted as a CrossShardReceipt; the credit is delivered to the recipient's shard as incoming receipts in a later round and applied exactly once. Value leaves the source shard at once and arrives on the target next round, so total value is conserved across the two rounds (tested). Misrouted/misdelivered receipts and malformed payloads are rejected. Built on the existing route()/CrossShardReceipt primitive. Tested."
        },
        {
          "id": "p4-i2",
          "text": "Confidential Sovereign Shards for national operations",
          "done": true,
          "status": "done",
          "note": "COMPLETE (cryptographic accountability layer): a sovereign shard can be designated confidential (ConfidentialShardSet); it publishes only a binding+hiding Blake3 commitment over its full chunk plus its PUBLIC state roots (ConfidentialChunk::seal), so the network folds it into the block's per-shard commitment root and tracks the shard's state-root progression without learning its transactions. An authorized auditor holding the chunk and its Blinding witness can open() the commitment, confirming both that it matches and that it yields the public state root everyone tracks. A mixed transparent/confidential commitment_root covers all shards in one block. Tested (seal/open, hiding under different blindings, binding against tampering, mixed root). HONEST SCOPE: this hides a shard's contents on-the-wire and in the network-kept ledger and binds the operator to a public state root; it is NOT execution privacy from the operator's own host — that needs a TEE/enclave (SGX/TDX) + remote attestation, hardware-bound and tracked under Confidential Intents (p5-i5), with which a confidential shard composes."
        }
      ],
      "doneCount": 3,
      "totalCount": 3,
      "percent": 100
    },
    {
      "id": 5,
      "title": "Phase 5 — Accounts & Interop",
      "tag": "Bridges",
      "description": null,
      "items": [
        {
          "id": "p5-i0",
          "text": "Account abstraction: human-readable accounts (e.g. usa.reserve.sov)",
          "done": true,
          "status": "done",
          "note": "COMPLETE: sov-accounts crate — NEAR-style account abstraction. (1) Hierarchical named accounts (names.rs): the dotted name space is an ownership hierarchy — reserve.sov owns usa.reserve.sov under the root registrar sov; parent/child/descendant tests. (2) Access keys (keys.rs): an account holds a SET of AccessKeys, each FullAccess or a restricted FunctionCall permission scoped to specific methods on one contract within a spend allowance — enabling key rotation, multi-device control, and delegated limited authority that a single controlling key cannot. (3) AccountRegistry (registry.rs) enforces the rules: top-level registration under the root, delegated sub-account creation (only a parent's full-access key may create under it), key add/remove/rotate that can never orphan an account (always at least one full-access key), and the authorize_call check the runtime consults. 21 tests. Wiring the registry into the runtime's transaction-authorization path (so a function-call key signs a real tx) is the integration follow-on; multi-signature M-of-N control is the separate item p5-i1."
        },
        {
          "id": "p5-i1",
          "text": "Multi-sig & institutional compliance tooling",
          "done": true,
          "status": "done",
          "note": "COMPLETE: sov-compliance crate — multi-signature custody + institutional compliance controls. (1) multisig.rs: MultisigPolicy names N signer keys and an M-of-N threshold (validated against empty/zero/over-threshold/duplicate signers); a Proposal (account + nonce + opaque action payload + expiry_height) is identified by its content hash; a MultisigApproval is an Ed25519 signature over the proposal bound to its signer — the same independently-verifiable, attributable model the chain uses for finality votes; authorization requires at least `threshold` DISTINCT authorized signers' valid approvals on a non-expired proposal, and approvals from non-signers, with bad signatures, or duplicated are ignored. (2) controls.rs: a per-account CompliancePolicy with a regulator freeze (blocks all outgoing), allow-list/deny-list counterparty control (KYC/sanctions), and a rolling spend-velocity SpendLimit; check_transfer is a pure decision function returning a specific ComplianceError or the updated SpendWindow. 15 tests. These are authorization/policy primitives; enforcing them in the runtime's transfer/authorization path (and storing each account's policy in the ledger) is the integration follow-on — the same boundary as p5-i0."
        },
        {
          "id": "p5-i2",
          "text": "NEAR-style Intents framework: sign one intent, solvers settle cross-chain",
          "done": true,
          "status": "done",
          "note": "COMPLETE (on-chain core): sov-intents — a user signs one Intent (give X of asset A, want >= Y of asset B, expiry); a solver submits a Settlement; settle() verifies (signature, expiry, min-delivery, both sides funded) and atomically swaps between owner and solver. Assets span native SOV and pooled BTC/ZEC/SOL. Runs over a Balances trait (tested with a mock; wires to ledger+pool). Solver competition is off-chain; settlement+verification on-chain. Tested."
        },
        {
          "id": "p5-i3",
          "text": "Native cross-chain consensus pool: validator-attested BTC/ZEC/SOL deposits + USD price oracle",
          "done": true,
          "status": "done",
          "note": "COMPLETE: sov-bridge now spans the full pool lifecycle. The consensus core (validator-attested deposits credited on stake supermajority + stake-weighted-median USD oracle) is joined by: WITHDRAWALS/PEG-OUT (a WithdrawalAttestation finalized at stake supermajority debits the pool and emits a WithdrawalAuthorization; replay-proof per-(account,asset) nonces; overdraw rejected); a committable pool_root() over pooled balances/reserves/nonces/credited deposits for block-header inclusion; a DepositWatcher trait + MockWatcher dev simulator (the seam that produces attestations — real watchers connect to live BTC/ZEC/SOL nodes); and THRESHOLD-SIGNATURE CUSTODY (ThresholdCustody) where locked funds sit at an MPC group key (sov-mpc) no single party holds, so a peg-out needs both a stake supermajority AND a threshold of key-share signers. 18 tests. Remaining: trust model (B) in-protocol light clients, and embedding pool_root in the live BlockHeader (P8 node work)."
        },
        {
          "id": "p5-i4",
          "text": "MPC Chain Signatures: one account controls keys on BTC/ETH/SOL (no bridge)",
          "done": true,
          "status": "done",
          "note": "COMPLETE (Ed25519): NEW crate sov-mpc wraps the AUDITED frost-ed25519 (ZcashFoundation FROST). Real distributed key generation (the committee jointly generates the key; no party ever holds the whole secret), M-of-N threshold signing, and verification under the group public key — which IS the external address. Tested: t-of-n DKG and trusted-dealer keygen, any threshold subset signs, fewer-than-threshold cannot, signatures bind to the message, distinct groups have distinct keys. Ed25519 covers Solana and SOV-native keys; secp256k1-Schnorr (Bitcoin Taproot) plugs into the identical FROST API; ECDSA (Ethereum/legacy Bitcoin) needs a separate GG-style ECDSA-MPC (follow-on). Used by the pool's threshold custody (p5-i3)."
        },
        {
          "id": "p5-i5",
          "text": "Confidential Intents: TEE-executed private intents (sender hidden)",
          "done": true,
          "status": "done",
          "note": "COMPLETE (cryptography + attestation verification): NEW crate sov-confidential. A user seals an intent to an executor's X25519 key with AUDITED crypto_box (X25519 + XChaCha20-Poly1305), using a fresh ephemeral sender key per intent so the ciphertext hides both contents and sender; only the executor can open it. An Attestation binds an enclave code measurement to the executor's key, signed by an authority; a relying party verifies the signature AND that the measurement matches the enclave it expects before sealing (seal_to_attested composes verify-then-seal). 12 tests. HONEST SCOPE: the encryption and attestation VERIFICATION are real and tested; keeping the intent confidential from the executor's own host requires opening/executing inside a genuine SGX/TDX enclave, and a real hardware attestation quote needs that hardware — the verifier is identical so a real quote slots in. The enclave runtime is the hardware-bound remainder."
        },
        {
          "id": "p5-i6",
          "text": "Sovereign cap tables: on-chain ownership registries (unit-conserving)",
          "done": true,
          "status": "done",
          "note": "COMPLETE: sov-captable — a sovereign issuer issues a fixed-supply instrument; the cap table records exact per-holder units with a hard CONSERVATION invariant (holdings always sum to total_units), transfers that move ownership without minting/burning, and ownership-percentage (bps) queries. Tested (conservation across many transfers, overdraw rejection, Borsh round-trip)."
        }
      ],
      "doneCount": 7,
      "totalCount": 7,
      "percent": 100
    },
    {
      "id": 6,
      "title": "Phase 6 — Governance, Compute & Reserve",
      "tag": "Sovereign",
      "description": null,
      "items": [
        {
          "id": "p6-i0",
          "text": "Bitcoin-style on-chain governance: miner-signaled soft-fork activation (BIP-9 version bits + BIP-8 mandatory activation) — hashpower consensus, not stake/holder voting",
          "done": true,
          "status": "done",
          "note": "Crate sov-governance: BIP-9 threshold-state machine + BIP-8 lockinontimeout over miner-signal windows, deterministic, 18 tests. Per directive, governance is decided by hashpower (miners), never by stake or token-holder voting. Signal bits wire into the live block header in Phase 8."
        },
        {
          "id": "p6-i1",
          "text": "Native DePIN compute marketplace: rent & use bare-metal Apple Silicon (M-series) — escrowed SOV jobs, validator-attested disputes, bond slashing, stake-weighted compute-price oracle",
          "done": true,
          "status": "done",
          "note": "Crate sov-compute, 37 tests. The real 'AI layer' substrate: off-chain AI rents M-series nodes and pays in SOV. On-chain autonomous 'agents' were dropped as out of scope — redundant with sov-accounts scoped access keys + allowances (a bot just holds a function-call key and submits intents/txs). Honest boundary: Apple Silicon has no SGX/TDX, so provider trust is economic (bond + slashing + reputation + validator-attested disputes), not hardware attestation; execution is off-chain."
        },
        {
          "id": "p6-i2",
          "text": "Geopolitical / reserve modeling tooling",
          "done": true,
          "status": "done",
          "note": "Crate sov-reserve, 38 tests. Deterministic emission/float/lock + multi-asset reserve projections from real protocol policies (mining/staking curves, pool reserves) under explicit, labeled assumptions. Honesty enforced by a Real-vs-Assumed provenance type; no invented real-world facts."
        }
      ],
      "doneCount": 3,
      "totalCount": 3,
      "percent": 100
    },
    {
      "id": 7,
      "title": "Phase 7 — Verification & Validity Assurance",
      "tag": "Trust",
      "description": "Guarantee the validity of EVERYTHING. A reserve asset for nations cannot have \"probably correct\" rules. Every state transition, balance, and consensus decision must be provably valid, reproducible, and independently re-checkable.",
      "items": [
        {
          "id": "p7-i0",
          "text": "Formal specification of the state transition function (machine-readable spec)",
          "done": true,
          "status": "done",
          "note": "Normative STF spec at chain/docs/state-transition.md — every rule (auth, authz, nonce, transfer, mine, stake, unstake, vesting, contracts, conserve, cap, determinism) with preconditions/effects/postconditions, cross-referenced to code + a passing test, and machine-checked by sov-verify/tests/conformance.rs against the real runtime. Mechanized model-checking (TLA+/Stateright) is p7-i1, not claimed here."
        },
        {
          "id": "p7-i1",
          "text": "Consensus safety & liveness model checking (TLA+ / Stateright)",
          "done": true,
          "status": "done",
          "note": "sov-verify/tests/consensus_model.rs: exhaustive bounded model check over all validator sets up to 5 members × stakes 1–3 and EVERY vote configuration, run against the production ValidatorSet::is_supermajority predicate. Verifies BFT safety (no conflicting finalization under <1/3 byzantine — quorum intersection) and liveness (honest supermajority finalizes, no premature finality), 100k+ configs. Std-only (no external model-checker dep); a TLA+/Stateright spec is optional complementary future work."
        },
        {
          "id": "p7-i2",
          "text": "Protocol-wide invariants: supply cap never exceeded, value conservation, no double-spend, no unauthorized mint",
          "done": true,
          "status": "done",
          "note": "Crate sov-verify: exact-integer check_ledger (supply ≤ cap, mined ≤ mining_budget, staked ≤ staking_budget) + check_transition (Δsupply == Δmined + Δstaked ⇒ value conserved + no unauthorized mint, emission monotonic). 11 unit tests. No-double-spend is nonce-enforced and proven by the replay test (p7-i4)."
        },
        {
          "id": "p7-i3",
          "text": "Property-based testing & coverage-guided fuzzing across every module",
          "done": true,
          "status": "done",
          "note": "proptest suite (sov-verify/tests/properties.rs): invariants hold over random tx sequences on a real chain, Borsh round-trips, 'decode arbitrary bytes never panics', exact Balance arithmetic, emission-curve monotonicity. Coverage-guided libFuzzer targets in chain/fuzz/ (signedtx/block/account decode + accountid) run via cargo +nightly fuzz; the stable proptest decode test exercises the same surface on every CI."
        },
        {
          "id": "p7-i4",
          "text": "Deterministic replay & cross-node state-root agreement checks",
          "done": true,
          "status": "done",
          "note": "sov-verify integration test drives a real Blockchain (PoW mint + transfer + stake), checks the p7-i2 invariants across every transition, then replays the blocks into an independent node and asserts byte-identical state_root at every height. Deterministic, no floats."
        },
        {
          "id": "p7-i5",
          "text": "Conformance test vectors (known-answer tests for crypto, serialization, execution)",
          "done": true,
          "status": "done",
          "note": "Committed vectors (crates/verify/tests/vectors/transactions.json) emitted by the real sov-katgen; sov-verify/tests/kat.rs re-derives every field — Ed25519 public key + signature, Blake3 tx id, Borsh signing bytes and full signed-tx encoding — and asserts byte-for-byte equality, and that signatures verify. Guards against any unintended crypto/serialization drift."
        },
        {
          "id": "p7-i6",
          "text": "Smart-contract static analysis & formal verification gates in CI",
          "done": true,
          "status": "done",
          "note": ".github/workflows/ci.yml gates: fmt + clippy -D warnings, full workspace tests, a named 'verify' job (invariants / model-check / conformance / KAT / fault-injection), a 'contracts' job (wasm32 clippy -D warnings + release build = guest static analysis), a 'reproducible' job, and a nightly 'fuzz targets build' job. The verification suite is a required check."
        },
        {
          "id": "p7-i7",
          "text": "Reproducible / verifiable builds (bit-for-bit binary attestation)",
          "done": true,
          "status": "done",
          "note": "VERIFIED bit-for-bit: scripts/reproducible-build.sh built sov-node / sov-miner / sov-katgen twice from clean targets with identical SHA-256 (locally + CI 'reproducible' job). Determinism via committed Cargo.lock + --locked, codegen-units=1 / lto / panic=abort, path remapping + fixed SOURCE_DATE_EPOCH. Canonical pinned environment in chain/Dockerfile (FROM rust:1.93.1) emits SHA256SUMS as the attestation. See chain/docs/reproducible-builds.md."
        },
        {
          "id": "p7-i8",
          "text": "Continuous testnet validation, chaos testing & fault injection",
          "done": true,
          "status": "done",
          "note": "Continuous chaos simulation (sov-verify/tests/chaos.rs): 1,200 seeded randomized rounds over two replica nodes — valid blocks (cross-node agreement + invariants checked every round), injected faults (forged roots / broken link / tampered signature, all rejected with the chain unmoved), and finalization, holding safety throughout. Plus the discrete fault-injection suite (fault_injection.rs, incl. equivocation→slashing). Note: live multi-machine testnet chaos is the Phase 8 operational counterpart of this deterministic harness."
        },
        {
          "id": "p7-i9",
          "text": "External security audits, bug bounty & public invariant dashboard",
          "done": false,
          "status": "in_progress",
          "note": "All TOOLING delivered: public invariant dashboard (Verification & Validity panel), SECURITY.md (disclosure + bug-bounty program + audit scope), internal security review + threat model + audit-readiness checklist (chain/docs/security-review.md), and reproducible builds for binary attestation. The ONLY remaining piece is the external third-party audit + live bug bounty — real-world engagements deliberately NOT faked. Mainnet is gated on a completed external audit."
        }
      ],
      "doneCount": 9,
      "totalCount": 10,
      "percent": 90
    },
    {
      "id": 8,
      "title": "Phase 8 — Node Daemon & RPC",
      "tag": "Daemon",
      "description": null,
      "items": [
        {
          "id": "p8-i0",
          "text": "Long-running node daemon: persistent state across restarts, scheduled block production & import",
          "done": true,
          "status": "done",
          "note": "sov-rpc `Daemon` + `sov-rpcd` binary: boots from a chain-spec, serves JSON-RPC, produces blocks every block_time_ms (scheduled), and PERSISTS to an append-only block log. State resumes across restarts by deterministic REPLAY of the log through the validated import path (never trusting a snapshot); integration test verifies a restart reaches a byte-identical state_root. FINALITY is persisted too: an append-only approval log (approvals.log) is replayed on boot, so a restarted node recovers which blocks crossed the stake supermajority — not just ledger state (integration test: a node with NO validator keys still sees a pre-restart block as final). Pure-Rust std-only ⇒ runs on macOS/Windows/Linux (CI matrix enforces)."
        },
        {
          "id": "p8-i1",
          "text": "Production P2P over the network: peer discovery and block/tx/approval sync beyond loopback",
          "done": true,
          "status": "done",
          "note": "sov-rpc `p2p` module (`P2p`/`P2pHandle`/`P2pConfig`) over sov-network `TcpNode`. AUTHENTICATED HANDSHAKE: a signed `Hello` binds chain_id + genesis_hash + Ed25519 key possession, so a peer on a different chain or fork is never trusted (its blocks/txs/approvals are dropped). HANDSHAKE-GATED GOSSIP: applies and re-broadcasts (each at most once) blocks→import, transactions→mempool, approvals→finality. CATCH-UP SYNC: a late joiner with an empty chain syncs to network height via Status-driven GetBlock/BlockResponse over targeted sends. `Node::import_block` applies peer blocks through the same validated, re-executed import path (trustless even among authenticated peers). The daemon gossips the blocks + approvals it produces. 4 multi-node integration tests over real loopback TCP prove: gossip+finality propagation, late-join catch-up, the daemon gossip path, and rejection of a wrong-genesis peer. Builds on TcpNode's existing TCP framing + transitive peer discovery."
        },
        {
          "id": "p8-i2",
          "text": "JSON-RPC API: submit transactions, query blocks/accounts/state, mining & pool endpoints",
          "done": true,
          "status": "done",
          "note": "sov-rpc crate: real std-only HTTP/1.1 + JSON-RPC 2.0 server over Arc<Mutex<Node>>, worker pool + graceful shutdown. Methods: health/chainId/getHeight/getSupply/getAccount/getBalance/getNonce/getBlock(ByHeight|ByHash)/getHead/getStateRoot/getDifficulty/getProposer/getMempoolSize/isFinal + getPoolReserve/getPoolBalance/getMiners + submitTransaction. Integration test does real round-trips over a live node (queries, signed-tx submit, duplicate rejection, JSON-RPC error codes)."
        },
        {
          "id": "p8-i3",
          "text": "Miner & wallet clients connect over RPC (external miners submit Mine solutions to the live node)",
          "done": true,
          "status": "done",
          "note": "sov-rpc `RpcClient` (std-only HTTP/JSON-RPC, types-only deps — no cycle): query height/supply/account/balance/nonce/block/difficulty/mempool, `transfer` (build+sign+submit), and `mine_block` (reads live head+difficulty, does real SHA-256d PoW against the per-miner challenge, submits the solution). Binaries `sov-rpc-miner` (external miner against a live node) and `sov-wallet` (balance + transfer). Integration test mines a real block + transfers over RPC against a live daemon."
        },
        {
          "id": "p8-i4",
          "text": "Node config, keystore, chain-spec/genesis loading, graceful start/stop & state persistence",
          "done": true,
          "status": "done",
          "note": "sov-rpc daemon module: `NodeConfig` (rpc addr/workers, data dir, block time, mempool), `ChainSpec` (chain_id/timestamp/policy preset/accounts → GenesisConfig), `Keystore` (validator seeds → keypairs) — all JSON, loaded by sov-rpcd without recompiling. Graceful start/stop via `DaemonHandle::shutdown` (stops production + RPC, joins threads). State persistence = an append-only block log (ledger/height/roots) PLUS an append-only approval log (finality) replayed on boot. Tests cover chain-spec→genesis, persist/resume of state, and finality surviving a restart. (Keystore seeds are plaintext — fine for testnet; encryption/HSM is a mainnet hardening step, noted in code.)"
        }
      ],
      "doneCount": 5,
      "totalCount": 5,
      "percent": 100
    },
    {
      "id": 9,
      "title": "Phase 9 — Block Explorer & Observability",
      "tag": "Visibility",
      "description": null,
      "items": [
        {
          "id": "p9-i0",
          "text": "Chain indexer: ingest blocks, transactions & receipts into a queryable store",
          "done": true,
          "status": "done",
          "note": "explorer/ (its own zero-dependency Node project): `src/indexer.js` backfills from genesis and follows the head, ingesting blocks + transactions into `src/store.js` (in-memory, ring-capped, with indices). Receipts roots are indexed; per-tx receipts aren't exposed by the node RPC, so they're honestly omitted rather than fabricated. Proven against a live sov-rpcd devnet."
        },
        {
          "id": "p9-i1",
          "text": "Search by transaction hash, block height/hash, account & shard",
          "done": true,
          "status": "done",
          "note": "`Store.search` classifies a query into block height, block/tx hash (0x-64hex), or account, backed by real indices (height→block, hash→height, txId→tx, account→txIds). Unknown hashes are resolved against the node. (Shard search is N/A: the live runtime is single-ledger; sharding is a built-but-unwired subsystem.)"
        },
        {
          "id": "p9-i2",
          "text": "REST + GraphQL API exposing indexed chain data",
          "done": true,
          "status": "done",
          "note": "REST (`src/rest.js`: /api/status, blocks, block/:ref, tx/:id, account/:id, supply, validators, miners, analytics, search) PLUS a hand-rolled, zero-dependency GraphQL engine (`src/graphql.js`: lexer + recursive-descent parser + executor; queries with arguments, nested selections, aliases) over the same store. Both verified end-to-end against a live node."
        },
        {
          "id": "p9-i3",
          "text": "Web UI: blocks, transactions, accounts, validators & supply stats",
          "done": true,
          "status": "done",
          "note": "Self-contained web UI (`web/`: index.html + style.css + app.js, institutional Treasury aesthetic matching the README/dashboard, hand-built inline-SVG seal): a hash-routed SPA — overview, blocks, block & tx detail, accounts, validators/miners, supply stats — over the REST API. Served by the explorer's std-http server."
        },
        {
          "id": "p9-i4",
          "text": "Real-time live feed (WebSocket) of new blocks & transactions",
          "done": true,
          "status": "done",
          "note": "Live feed via a hand-rolled RFC 6455 WebSocket server (`src/ws.js`) over Node's http upgrade event — zero dependencies. Broadcasts new blocks + transactions as the indexer ingests them; the UI shows a live ticker. Smoke-tested (`devnet/ws-check.mjs`): 101 handshake + real block/tx frames observed."
        },
        {
          "id": "p9-i5",
          "text": "Validity view: finality status, state roots & verification proofs per block",
          "done": true,
          "status": "done",
          "note": "Validity view: per-block finality (live `sov_isFinal`, re-checked for recent blocks each sync), the committed state/tx/receipts roots, and the >2/3-stake Doomslug BFT explanation. Surfaces what the verification layer guarantees, per block."
        },
        {
          "id": "p9-i6",
          "text": "Analytics dashboards: circulating supply, staking ratio, issuance curve",
          "done": true,
          "status": "done",
          "note": "Analytics: circulating supply (total/mined/staked), staking ratio, minted-of-21M-cap, and an issuance curve (inline SVG) built from supply sampled live per height. All real, observed values — nothing extrapolated or faked."
        },
        {
          "id": "p9-i7",
          "text": "Built as its own project in explorer/, indexing a live SOV node (real data only)",
          "done": true,
          "status": "done",
          "note": "Built as its own project in `explorer/` (separate from the Rust workspace), ZERO runtime dependencies (Node standard library only). Indexes a live SOV node over JSON-RPC — REAL data only, nothing simulated. Enabled by one additive node method, `sov_getBlockDigest` (block hash + canonical tx ids, which a client cannot recompute without Borsh/Blake3). 13 unit tests pass; full stack proven e2e against a sov-rpcd devnet (real signed transfer → block → indexed → REST/GraphQL/WS)."
        }
      ],
      "doneCount": 8,
      "totalCount": 8,
      "percent": 100
    },
    {
      "id": 10,
      "title": "Phase 10 — JavaScript/TypeScript SDK & Client Library",
      "tag": "SDK",
      "description": "A standalone Node/TypeScript SDK (sdk/, separate from the Rust workspace) giving wallets, dApps and tooling a high-level client over SOV: SOV unit math, AccountId validation, Ed25519 keys, wire types, a Borsh transaction encoder/signer verified byte-for-byte against the Rust node (KAT vectors), a live JSON-RPC client, and a Wallet helper. Transactions it builds are node-submittable — proven by a live end-to-end test. No fabricated data.",
      "items": [
        {
          "id": "p10-i0",
          "text": "SOV unit math (SOV<->grains, 8 decimals) and amount handling",
          "done": true,
          "status": "done",
          "note": "Real & unit-tested in sdk/src/units.ts. BigInt grains (never floats), 1 SOV = 100_000_000 grains, hard cap 21,000,000 SOV; parses/formats decimal strings, rejects negatives and over-cap. Mirrors chain/crates/primitives/src/amount.rs."
        },
        {
          "id": "p10-i1",
          "text": "AccountId validation & name hierarchy helpers (matching the protocol rules)",
          "done": true,
          "status": "done",
          "note": "Real & unit-tested in sdk/src/account.ts. Validation matches chain/crates/primitives/src/account.rs exactly (length 2..=64 bytes; a-z 0-9 - _ .; no leading/trailing/adjacent separators). Helpers: parent() (usa.reserve.sov -> reserve.sov), topLevel(), isTopLevel()."
        },
        {
          "id": "p10-i2",
          "text": "Ed25519 keys, signing & verification (audited library)",
          "done": true,
          "status": "done",
          "note": "Real & unit-tested in sdk/src/keys.ts using @noble/ed25519 + @noble/hashes (audited). generate(), fromSeed(32-byte seed, matching the node's Keypair::from_seed), sign/verify, public key as hex. Pinned to a known seed->pubkey vector."
        },
        {
          "id": "p10-i3",
          "text": "Core types & transaction builder (Account/Tx/Block/Receipt)",
          "done": true,
          "status": "done",
          "note": "Real & unit-tested in sdk/src/types.ts + tx-builder.ts + borsh.ts. Interfaces mirror the chain's serde JSON shapes. The builder now signs the node's CANONICAL Borsh signing bytes and derives the real Blake3 transaction id — wire-compatible, proven byte-for-byte by KAT vectors (p10-i6) and by a live e2e (the node accepts and includes an SDK-built transfer). The json-v0-placeholder scheme is gone."
        },
        {
          "id": "p10-i4",
          "text": "Typed JSON-RPC client (SovClient) targeting the Phase 8 node RPC",
          "done": true,
          "status": "done",
          "note": "sdk/src/rpc.ts: SovClient over a real fetch transport (Node 18+), JSON-RPC 2.0 with the node's named-object params. Typed methods: chainId/getHeight/getSupply/getAccount/getBalance/getNonce/getBlockByHeight|Hash/getBlockDigest/getHead/getStateRoot/getDifficulty/getProposer/getMempoolSize/isFinal/submitTransaction. (No getReceipt — the node exposes no receipt method, so it is honestly omitted, not faked.) Transport is injectable for tests; verified live against sov-rpcd."
        },
        {
          "id": "p10-i5",
          "text": "High-level wallet & dApp helpers over the client",
          "done": true,
          "status": "done",
          "note": "sdk/src/wallet.ts: a Wallet binds a keypair + account to a SovClient. balance()/nonce()/state() reads; send(action) and transfer()/stake() build+sign+submit with automatic nonce selection; awaitInclusion(txId) scans new block digests for inclusion + finality. All real round-trips; proven by a live e2e (SDK transfer accepted, included, recipient balance +1 SOV)."
        },
        {
          "id": "p10-i6",
          "text": "Known-answer encoding/signing vectors shared with the Rust crates",
          "done": true,
          "status": "done",
          "note": "sdk/src/borsh.ts: a byte-exact Borsh encoder for Transaction/Action + Blake3 tx id (@noble/hashes). Vectors generated from the Rust node (`cargo run -p sov-rpc --bin sov-katgen > sdk/vectors/transactions.json`); sdk/test/borsh.test.ts asserts signing bytes, tx id, signature, and full signed-tx Borsh match byte-for-byte across 5 action vectors (26 assertions). This is the proof of wire compatibility."
        }
      ],
      "doneCount": 7,
      "totalCount": 7,
      "percent": 100
    }
  ],
  "phasesError": null
};
