/**
 * Byte-exact Borsh encoding of SOV transaction types, and the Blake3 transaction
 * id derived from it.
 *
 * The node's CANONICAL signing payload is the Borsh encoding of the
 * `Transaction` (`chain/crates/types/src/transaction.rs::signing_bytes`), and a
 * transaction's id is the Blake3 hash of those bytes. This module reproduces
 * that layout exactly — and `test/borsh.test.ts` proves it byte-for-byte against
 * known-answer vectors generated by the Rust `sov-katgen` tool. With this in
 * place the SDK can produce transactions the node accepts.
 *
 * Layout (little-endian, matching the Rust `borsh` derives):
 *   - integers: fixed-width little-endian (u64 = 8 bytes, u128 = 16 bytes);
 *   - `String` / `AccountId`: u32 length prefix then UTF-8 bytes;
 *   - `[u8; 32]` (public key): 32 raw bytes, no prefix;
 *   - `Vec<u8>`: u32 length prefix then bytes;
 *   - enum (`Action`): a u8 variant index then the variant's fields, in
 *     declaration order (Transfer=0, ClaimVesting=1, Deploy=2, Call=3,
 *     Shielded=4, HtlcLock=5, HtlcClaim=6, HtlcRefund=7).
 *     The pre-Nakamoto Mine/MineShielded mint transactions AND the Stake/
 *     Unstake actions were REMOVED from the protocol (issuance is the block
 *     coinbase and there is no proof-of-stake), shifting the indices of every
 *     later variant — regenerate vectors when the enum changes.
 */

import { blake3 } from "@noble/hashes/blake3.js";
import type { Action, BlockHeader, SignedTransaction, Transaction } from "./types.js";

/** Error thrown for inputs that cannot be Borsh-encoded. */
export class BorshError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BorshError";
  }
}

export function hexToBytes(hex: string): Uint8Array {
  const s = hex.startsWith("0x") ? hex.slice(2) : hex;
  if (s.length % 2 !== 0 || /[^0-9a-fA-F]/.test(s)) {
    throw new BorshError(`invalid hex string: ${hex}`);
  }
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

export function bytesToHex(bytes: Uint8Array): string {
  let s = "";
  for (const b of bytes) s += b.toString(16).padStart(2, "0");
  return s;
}

/** A minimal little-endian Borsh writer for the SOV transaction types. */
export class BorshWriter {
  private buf: number[] = [];

  u8(n: number): this {
    this.buf.push(n & 0xff);
    return this;
  }

  private uint(value: bigint, bytes: number): this {
    if (value < 0n) throw new BorshError("cannot encode a negative integer");
    let v = value;
    for (let i = 0; i < bytes; i++) {
      this.buf.push(Number(v & 0xffn));
      v >>= 8n;
    }
    if (v !== 0n) throw new BorshError(`integer does not fit in ${bytes} bytes`);
    return this;
  }

  u32(n: number | bigint): this {
    return this.uint(BigInt(n), 4);
  }

  u64(n: number | bigint): this {
    return this.uint(BigInt(n), 8);
  }

  u128(n: number | bigint): this {
    return this.uint(BigInt(n), 16);
  }

  raw(b: Uint8Array): this {
    for (const x of b) this.buf.push(x);
    return this;
  }

  fixed(b: Uint8Array, len: number): this {
    if (b.length !== len) throw new BorshError(`expected ${len} bytes, got ${b.length}`);
    return this.raw(b);
  }

  string(s: string): this {
    const enc = new TextEncoder().encode(s);
    this.uint(BigInt(enc.length), 4);
    return this.raw(enc);
  }

  vecU8(b: Uint8Array): this {
    this.uint(BigInt(b.length), 4);
    return this.raw(b);
  }

  bytes(): Uint8Array {
    return Uint8Array.from(this.buf);
  }
}

function writeAction(w: BorshWriter, action: Action): void {
  switch (action.type) {
    case "transfer":
      w.u8(0).string(action.to).u128(BigInt(action.amount));
      break;
    case "claim_vesting":
      w.u8(1);
      break;
    case "deploy":
      w.u8(2).vecU8(Uint8Array.from(action.code));
      break;
    case "call":
      w.u8(3)
        .string(action.contract)
        .u64(action.gas_limit)
        .vecU8(Uint8Array.from(action.calldata ?? []));
      break;
    case "shielded":
      w.u8(4).vecU8(Uint8Array.from(action.bundle));
      break;
    case "htlc_lock":
      w
        .u8(5)
        .string(action.recipient)
        .u128(BigInt(action.amount))
        .fixed(hexToBytes(action.hashlock), 32)
        .u64(action.timeout_height);
      break;
    case "htlc_claim":
      w.u8(6).fixed(hexToBytes(action.htlc_id), 32).vecU8(Uint8Array.from(action.preimage));
      break;
    case "htlc_refund":
      w.u8(7).fixed(hexToBytes(action.htlc_id), 32);
      break;
    default: {
      const _never: never = action;
      throw new BorshError(`unknown action: ${JSON.stringify(_never)}`);
    }
  }
}

/** Hybrid-key marker: a `hybrid65:`-prefixed public key or signature JSON string
 * selects the post-quantum scheme (`0x01`); anything else is Ed25519 (`0x00`). */
const HYBRID_PREFIX = "hybrid65:";
/** Byte lengths of each versioned key/signature's raw payload. */
const ED25519_PK_LEN = 32;
const HYBRID_PK_LEN = 32 + 1952; // Ed25519 ‖ ML-DSA-65
const ED25519_SIG_LEN = 64;
const HYBRID_SIG_LEN = 64 + 3309; // Ed25519 ‖ ML-DSA-65

/** Borsh-encode the versioned public key from its JSON form, scheme byte first —
 * mirrors the node's `PublicKey` enum: Ed25519 (`0x00` + 32 bytes) or hybrid
 * Ed25519 + ML-DSA-65 (`0x01` + 1984 bytes). The scheme is thereby committed
 * inside the signed payload (cryptographic agility — no cross-scheme replay). */
function writeVersionedPublicKey(w: BorshWriter, publicKey: string): void {
  if (publicKey.startsWith(HYBRID_PREFIX)) {
    const bytes = hexToBytes(publicKey.slice(HYBRID_PREFIX.length));
    if (bytes.length !== HYBRID_PK_LEN) {
      throw new BorshError(`hybrid65 key must be ${HYBRID_PK_LEN} bytes, got ${bytes.length}`);
    }
    w.u8(1).fixed(bytes, HYBRID_PK_LEN);
  } else {
    w.u8(0).fixed(hexToBytes(publicKey), ED25519_PK_LEN);
  }
}

/** The canonical Borsh signing bytes for a transaction (what the node signs). */
export function encodeTransaction(tx: Transaction): Uint8Array {
  const w = new BorshWriter();
  w.string(tx.signer);
  writeVersionedPublicKey(w, tx.public_key);
  w.u64(tx.nonce);
  writeAction(w, tx.action);
  return w.bytes();
}

/** Full Borsh of a signed transaction: the tx signing bytes then the versioned
 * signature (scheme byte + raw bytes), matching the node's `Signature` enum —
 * Ed25519 (`0x00` + 64) or hybrid Ed25519 + ML-DSA-65 (`0x01` + 3373). */
export function encodeSignedTransaction(signed: SignedTransaction): Uint8Array {
  const txBytes = encodeTransaction(signed.transaction);
  const hybrid = signed.signature.startsWith(HYBRID_PREFIX);
  const sig = hexToBytes(hybrid ? signed.signature.slice(HYBRID_PREFIX.length) : signed.signature);
  const expected = hybrid ? HYBRID_SIG_LEN : ED25519_SIG_LEN;
  if (sig.length !== expected) {
    throw new BorshError(`signature must be ${expected} bytes, got ${sig.length}`);
  }
  const out = new Uint8Array(txBytes.length + 1 + sig.length);
  out.set(txBytes, 0);
  out[txBytes.length] = hybrid ? 1 : 0;
  out.set(sig, txBytes.length + 1);
  return out;
}

/** The 32-byte transaction id: Blake3 of the canonical signing bytes. */
export function transactionIdBytes(tx: Transaction): Uint8Array {
  return blake3(encodeTransaction(tx));
}

/** The transaction id as `0x<hex>` (matches the node's `Hash` JSON form). */
export function transactionId(tx: Transaction): string {
  return `0x${bytesToHex(transactionIdBytes(tx))}`;
}

// --- Independent consensus re-derivation -----------------------------------
//
// The functions below recompute SOV's consensus-critical commitments — the block
// id (header hash), the transaction Merkle root, and the per-transaction ids —
// from raw bytes, in TypeScript, with NO shared code with the Rust node. They are
// the foundation of an independent verifier: anything that disagrees byte-for-byte
// with the node is a consensus divergence. Mirrors `chain/crates/crypto/src/merkle.rs`
// and `chain/crates/types/src/block.rs`.

const LEAF_PREFIX = 0x00;
const NODE_PREFIX = 0x01;

export function hashLeaf(leaf: Uint8Array): Uint8Array {
  const b = new Uint8Array(1 + leaf.length);
  b[0] = LEAF_PREFIX;
  b.set(leaf, 1);
  return blake3(b);
}

export function hashNode(left: Uint8Array, right: Uint8Array): Uint8Array {
  const b = new Uint8Array(1 + left.length + right.length);
  b[0] = NODE_PREFIX;
  b.set(left, 1);
  b.set(right, 1 + left.length);
  return blake3(b);
}

/**
 * The domain-separated binary Merkle root over ordered 32-byte `leaves`. Empty
 * input has a fixed root (`blake3([0x00])`); an odd node is promoted unchanged
 * (no last-leaf duplication). Byte-identical to the node's `merkle_root`.
 */
export function merkleRoot(leaves: Uint8Array[]): Uint8Array {
  if (leaves.length === 0) return blake3(Uint8Array.of(LEAF_PREFIX));
  let level = leaves.map(hashLeaf);
  while (level.length > 1) {
    const next: Uint8Array[] = [];
    for (let i = 0; i < level.length; i += 2) {
      const left = level[i] as Uint8Array;
      const right = level[i + 1];
      next.push(right === undefined ? left : hashNode(left, right));
    }
    level = next;
  }
  return level[0] as Uint8Array;
}

/** The transaction Merkle root committing to `transactions` in order (raw bytes). */
export function computeTxRootBytes(transactions: Transaction[]): Uint8Array {
  return merkleRoot(transactions.map(transactionIdBytes));
}

/** The transaction Merkle root as `0x<hex>` (matches the header's `tx_root`). */
export function computeTxRoot(transactions: Transaction[]): string {
  return `0x${bytesToHex(computeTxRootBytes(transactions))}`;
}

/** Byte-exact Borsh encoding of a block header (the bytes the node hashes). */
export function encodeBlockHeader(h: BlockHeader): Uint8Array {
  const w = new BorshWriter();
  w.u64(h.height);
  w.fixed(hexToBytes(h.prev_hash), 32);
  w.fixed(hexToBytes(h.tx_root), 32);
  w.fixed(hexToBytes(h.receipts_root), 32);
  w.fixed(hexToBytes(h.state_root), 32);
  w.u64(h.timestamp_ms);
  w.string(h.proposer);
  // BIP-9/8 miner-signaling bits (0 = signals nothing), hash-committed.
  w.u32(h.version_bits ?? 0);
  // Difficulty target in Bitcoin's compact "nBits" form, hash-committed.
  w.u32(h.bits ?? 0);
  // Nakamoto proof-of-work nonce (the miner grinds this to seal the block).
  w.u64(h.nonce ?? 0);
  return w.bytes();
}

/** The block id (`0x<hex>`): Blake3 of the Borsh-encoded header. */
export function blockHash(h: BlockHeader): string {
  return `0x${bytesToHex(blake3(encodeBlockHeader(h)))}`;
}
